openapi: 3.0.0
info:
  version: "1.0.0"
  title: API SCCON
  description: >-
    # Introdução

    Essa API fornece acesso ao serviço de seleção automática das melhores imagens, retornando os IDs para download.
    O serviço é autenticado, ou seja, necessita de um token de segurança para ser acessado.
    A obtenção deste token de segurança é realizada através do serviço de autenticação.


    **Como usar autenticação JWT**<br/>
    Adicionar header com:<br/>
    - Chave: 'Authorization'<br/>
    - Valor : Bearer {access_token}'

  contact:
    email: plataforma@sccon.com.br

tags:
  - name: Token
    description: Fornece o token de acesso para utilizar o serviço de busca de imagens.
  - name: Melhores Imagens
    description: Busca das melhores imagens. No retorno há a propriedade "ids", contendo os IDs das imagens, os quais poderão ser extraídos, tratados e usados no script de download.
x-tagGroups:
  - name: Autenticação
    tags:
      - Token
  - name: Imagens
    tags:
      - Melhores Imagens
security:
  - JWT Token: []
paths:
  /auth/token:
    get:
      tags:
        - Token
      summary: Acesso ao token
      security: []
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: password
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
              examples:
                response:
                  value:
                    - access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnYW1hYWdyaWN1bHR1cmEuY29tLmJyIiwic3ViIjoid2VzbGV5LnNpbHZhQHNjY29uLmNvbS5iciIsIm5hbWUiOiJXZXNsZXkgU2lsdmEiLCJleHAiOjE1OTg5MDQ3OTQ0NTAsImlhdCI6MTU5ODI5OTk5NDQ1MCwicm9sZXMiOlsiTUFOQUdFX1VTRVJTIiwiR0VORVJBVEVfV01TX1NFTEVDVEVEX0lNQUdFUyIsIkRPV05MT0FEX0lNQUdFX0FOQUxZVElDX1NSIiwiTUFOQUdFX09SR0FOSVpBVElPTlMiLCJHRVRfTU9TQUlDX0xJTksiLCJWSUVXIiwiRE9XTkxPQURfSU1BR0VfVklTVUFMIiwiRVhQRVJUX1BGIiwiRE9XTkxPQURfU1RBVFMiLCJET1dOTE9BRF9SQUFfU0hFRVQiLCJET1dOTE9BRF9JTUFHRV9TSEFQRSIsIkFDQ0VTU19EQVNIQk9BUkRfUEYiLCJET1dOTE9BRF9BTEVSVFMiLCJET1dOTE9BRCIsIk1BTkFHRV9DT05UUkFDVFMiLCJET1dOTE9BRF9JTUFHRV9BTkFMWVRJQyIsIkFVVE9NQVRJQ19XTVMiXX0.kpAJYGTXpWrV_QEnVUvC9soKojw-mLKmnVRsh8itst4
                      token_type: Bearer
                      iss: plataforma.sccon.com.br
                      sub: plataforma@sccon.com.br
                      name: Usuário do Serviço
                      exp: 1498742285823
                      iat: 1498655885823
                      roles:
                        - Download
                        - Search
        "401":
          description: Não autorizado
  /assets/best:
    post:
      tags:
        - Melhores Imagens
      summary: Buscar
      parameters:
        - name: byClouds
          in: query
          description: Usado para informar se a busca será feita usando o parâmetro de nuvens.
          schema:
            type: boolean
            default: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SceneFilterDTO"
      responses:
        "200":
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BestFeaturesDTO"
        "400":
          description: Solicitação inválida
        "401":
          description: Não autorizado
        "403":
          description: Proibido
servers:
  - url: https://plataforma.sccon.com.br/gama-api
components:
  securitySchemes:
    JWT Token:
      type: http
      scheme: bearer
      bearerFormat: JWT
  requestBodies:
    Token:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Token"
      required: true
  schemas:
    SceneFilterDTO:
      title: Filtros Imagens
      type: object
      required:
        - sort
        - pageSize
        - permissions
        - providers
      properties:
        sort:
          type: string
          description: Ordenação do resultado
        pageSize:
          type: integer
        providers:
          $ref: "#/components/schemas/Providers"
        startAcquiredDate:
          type: string
          description: Valor inicial para pesquisa por data de aquisição da imagem.
        endAcquiredDate:
          type: string
          description: Valor final para pesquisa por data de aquisição da imagem.
        wkts:
          type: array
          description: Geometria para usar como busca.
          items:
            type: string
        startCloudCover:
          type: number
          description: Valor inicial para pesquisa por porcentagem de preechimento por nuvem. Valores entre 0 e 1
        endCloudCover:
          type: number
          description: Valor final para pesquisa por porcentagem de preechimento por nuvem. Valores entre 0 e 1
        startBlackFill:
          type: number
          description: Valor inicial para pesquisa por porcentagem da imagem com preenchimento de bit do tipo black fill. Valores entre 0 e 1
        endBlackFill:
          type: number
          description: Valor final para pesquisa por porcentagem da imagem com preenchimento de bit do tipo black fill. Valores entre 0 e 1
        satelliteId:
          type: string
        startGSD:
          type: number
          description: Valor inicial para pesquisa por porcentagem de Ground Sample Distance. Valores entre 0 e 1
        endGSD:
          type: number
          description: Valor final para pesquisa por porcentagem de Ground Sample Distance. Valores entre 0 e 1
        stripId:
          type: string
          description: Id da faixa de passagem
        onlySSO:
          type: boolean
          description: Apenas satélites de órbita heliossíncrona
        ids:
          type: array
          items:
            type: string
      example:
        permissions:
          - assets.analytic:download
        sort: "acquired desc"
        pageSize: 30
        providers:
          - PSScene4Band
        startAcquiredDate: 2020-06-08T00:00:00.000Z
        endAcquiredDate: 2020-12-08T23:59:59.999Z
        wkts:
          - POLYGON ((-50.657959 -24.318317, -50.657959 -24.132342, -50.361328 -24.132342, -50.361328 -24.318317, -50.657959 -24.318317))
        startCloudCover: 0.0
        endCloudCover: 1.0
        startBlackFill: 0.0
        endBlackFill: 1.0
        onlySSO: false
    Providers:
      title: Fornecedor Imagem
      type: array
      enum:
        - PSScene4Band
    BestFeaturesDTO:
      title: Features
      type: object
      properties:
        area:
          type: number
        areaCovered:
          type: number
        percentCovered:
          type: number
        ids:
          type: array
          description: IDs das imagens que serão usados para download
          items:
            type: string
        features:
          type: array
          items:
            $ref: "#/components/schemas/FeatureDTO"
        geometry:
          type: object
          description: Geometria em GeoJson
        geometryCovered:
          type: object
          description: Geometria em GeoJson
      example:
        area: 620185337.7224793
        areaCovered: 620198111.901117
        percentCovered: 0
        ids:
          - '20201028_115834_1_0f44'
          - '20200930_124646_11_2231'
          - '20200930_124643_90_2231'
          - '20200926_124649_28_222b'
          - '20200724_121537_0f44'
          - '20200724_121537_1_0f44'
          - '20200724_121536_0f44'
          - '20200721_121204_100d'
          - '20200624_122027_1_0f32'
          - '20200624_122024_0f32'
          - '20200619_124553_57_222f'
          - '20200619_124549_28_222f'
        features:
          - id: "20201028_115834_1_0f44"
            properties:
              acquired: "2020-10-28T11:58:34.990Z"
              cloudCover:  0.0
              itemType:  "PSScene4Band"
            geometryClip: {"type":"Polygon","coordinates":[[[-50.657959,-24.264856407387065],[-50.657959,-24.210048772601922],[-50.64648369635342,-24.26279652042074],[-50.657959,-24.264856407387065]]]}
        geometry: {"type":"Polygon","coordinates":[[[-50.88813704764115,-24.23583401491114],[-50.8790126299585,-24.2341936260685],[-50.859490225791866,-24.147326757052458],[-50.86153453459264,-24.137393971975428],[-50.857079848739275,-24.136601545858184],[-50.84564450241759,-24.085718840910584],[-50.81594068111603,-24.091304695663283],[-50.77693034066423,-23.918116170496717],[-50.44456552860701,-23.98142987200855],[-50.4518561360926,-24.014120989883505],[-50.297125194433605,-24.043950171420263],[-50.30311442288242,-24.07050856346268],[-50.17096874850991,-24.047100428756256],[-50.15961080454576,-24.100007328457608],[-50.15652683534682,-24.11486618464955],[-50.31963293297251,-24.143757575531264],[-50.32879489534051,-24.184385010354717],[-50.328442070517525,-24.18445294210282],[-50.369697167377176,-24.367153119319276],[-50.52398350714663,-24.338083625569787],[-50.54546380841141,-24.43341359845337],[-50.87891096273286,-24.370705295219192],[-50.86329722703688,-24.30171587103075],[-50.87419536645799,-24.303672153499793],[-50.88268431966903,-24.264311286297396],[-50.88565625509144,-24.263755093461988],[-50.8842008985329,-24.257279340452126],[-50.88572575996744,-24.250208990676988],[-50.885063182958554,-24.250090074061266],[-50.88813704764115,-24.23583401491114]]]}
        geometryCovered: {"type":"MultiPolygon","coordinates":[[[[-50.525767763137125,-24.243549480286205],[-50.52504351065872,-24.24341909905686],[-50.53371842397334,-24.20351347411268],[-50.537735934439056,-24.18503245187769],[-50.53708769229196,-24.184915734165887],[-50.657959,-24.206678932565076],[-50.657959,-24.13550974014301],[-50.657959,-24.132342],[-50.6405058267672,-24.132342],[-50.54861827637921,-24.132342],[-50.478221186826175,-24.132342],[-50.389095842351544,-24.132342],[-50.361328,-24.132342],[-50.361328,-24.151143127002765],[-50.361328,-24.178121191805992],[-50.361328,-24.318317],[-50.51952957666303,-24.318317],[-50.58911032628478,-24.318317],[-50.60648997655654,-24.318317],[-50.657959,-24.318317],[-50.657959,-24.2673467836914],[-50.525767763137125,-24.243549480286205]],[[-50.478221186826175,-24.132342],[-50.4851375786832,-24.16335513325593],[-50.48319771848904,-24.15465679112277],[-50.478221186826175,-24.132342]],[[-50.60648997655654,-24.318317],[-50.58974566922688,-24.315298439949196],[-50.51584765492721,-24.30197656348054],[-50.60648997655654,-24.318317]],[[-50.525767763137125,-24.243549480286205],[-50.512979710139774,-24.30145954815152],[-50.51434155907742,-24.295292482342674],[-50.52487322021405,-24.247600373834626],[-50.525767763137125,-24.243549480286205]]],[[[-50.657959,-24.264856407387065],[-50.657959,-24.210048772601922],[-50.657959,-24.206678932565076],[-50.537735934439056,-24.18503245187769],[-50.52504351065872,-24.24341909905686],[-50.657959,-24.2673467836914],[-50.657959,-24.264856407387065]]]]}
    FeatureDTO:
      title: Feature
      type: object
      properties:
        links:
          $ref: "#/components/schemas/LinksDTO"
        permissions:
          type: array
          description: Downloads permitidos para a imagem
          items:
            type: string
        id:
          type: string
        "type":
          type: string
        properties:
          $ref: "#/components/schemas/FeaturePropertiesDTO"
        geometry:
          type: object
        geometryClip:
          type: object
        enableDownload:
          type: boolean
          description: Se a imagem permite download
    LinksDTO:
      title: Links
      type: object
      properties:
        thumbnail:
          type: string
        tms:
          type: string
        first:
          type: string
        next:
          type: string
        prev:
          type: string
        self:
          type: string
        assets:
          type: string
        activate:
          type: string
    FeaturePropertiesDTO:
      title: Properties
      type: object
      properties:
        acquired:
          type: string
        anomalousPixels:
          type: number
        blackFill:
          type: number
        cloudCover:
          type: number
        columns:
          type: integer
        epsgCode:
          type: integer
        gridCell:
          type: integer
        gsd:
          type: number
        instrument:
          type: string
        itemType:
          type: string
        originX:
          type: number
        originY:
          type: number
        pixelResolution:
          type: number
        provider:
          type: string
        published:
          type: string
        rows:
          type: integer
        satelliteId:
          type: string
        sunAzimuth:
          type: number
        sunElevation:
          type: number
        updated:
          type: string
        usableData:
          type: number
        viewAngle:
          type: number
        stripId:
          type: string
    Token:
      title: Token
      type: object
      properties:
        access_token:
          type: string
          readOnly: true
        token_type:
          type: string
          readOnly: true
        iss:
          type: string
          readOnly: true
        sub:
          type: string
          readOnly: true
        name:
          type: string
          readOnly: true
        exp:
          type: number
          readOnly: true
        iat:
          type: number
          readOnly: true
        roles:
          type: array
          enum:
            - Download
            - Search
          description: Permissões do usuário autenticado
          